project:
  type: website
  output-dir: docs
  resources:
    - "Material/**"
    
website:
  title: "STA 9750 Submission Material "
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://aratikalor26.github.io/STA9750-2025-FALL/"
  navbar:
    background: primary
    search: false

format:
  html:
    theme: flatly   # or pick another Bootswatch theme
    toc: false

editor:
  mode: source
